### ISSUE TITLE
IMK 選字窗改候選字尺寸

### ISSUE THREAD

**Issue by ShikiSuen** [y1lichen/ilimi-inputmethod#1]
你要用 IMK 選字窗的話，你就得用 Bridging Header 強制曝露一些內部函式。
系統要求是至少 macOS 10.14。

<img width="654" alt="image" src="https://user-images.githubusercontent.com/3164826/189377277-da7bf23a-52af-4821-b6b6-ec542d0f751c.png">

只是修改  "NSAttributedString.Key.font" 的話，沒有用。你可以 file 一份 apple bug report 且提及 FB11300759。
P.S.: 我在 FB11300759 裡面把 IMK 臭罵了一頓。根本就是嚴重缺乏單元測試的爛貨。

另外就是要注意 IMK 選字窗會被 NSMenu 與 Spotlight 擋住。解決方法：
https://github.com/gureum/gureum/issues/843#issuecomment-1230343044

**Comment by y1lichen** [comment]
已透過Bridging File使用setFontSize方法調整字體方法！感謝協助！

**Comment by ShikiSuen** [comment]
@y1lichen 忘記講了。bridging header 當中的 `(vChewing)` 請改成自己的 target 名稱。
