### ISSUE TITLE
使用選單中的反查注音、查碼功能時，無法複製&貼上

### ISSUE THREAD

**Issue by y1lichen** [y1lichen/ilimi-inputmethod#11]

**Comment by ShikiSuen** [comment]
因為 MainMenu.xib 缺失。
我有嘗試補上這個模組，卻發現輸入法有一些莫名其妙的異常，原因未知。

看來不能用 XIB 的手段，得用程式的手段補上 Global Main Menu。

P.S.: 這個選單不可見，但是負責了輸入法對自身視窗的各種剪貼簿熱鍵與「CMD+W」等熱鍵。

**Comment by y1lichen** [comment]
https://stackoverflow.com/questions/63969753/keyboard-shortcuts-not-working-in-menubar-application-for-macos
查看了一輪stackoverflow確實有相關問題，但尚未找到解方。輸入法和menubar app情況似乎又不完全一樣。

**Comment by y1lichen** [comment]
己修正！
