### ISSUE TITLE
可選擇選字為1-9或0-8

### ISSUE THREAD

**Issue by y1lichen** [y1lichen/ilimi-inputmethod#12]
原廠蝦米是用0-8選字

**Comment by y1lichen** [comment]
如 https://github.com/pkamb/NumberInput_IMKit_Sample/issues/3 所說，setSelectionKey api並不可用，選字碼提示並不會顯示。如此會對使用0-8選字的使用者造成困擾，因此要再新增選項是能使用預設1-9選字的畫面（使用者得在心裡自行減1計算選字碼）。

**Comment by ShikiSuen** [comment]
Apple Radar Report #FB13706685 sent. cc @xhacker .

<img width="781" alt="image" src="https://github.com/y1lichen/ilimi-inputmethod/assets/3164826/73855870-1d88-413b-8ea7-0d2a4b2178c8">

**Comment by ShikiSuen** [comment]
@y1lichen 等 WWDC2024 看看有沒有 InputMethodKit2。
如果沒有的話，就當這個問題永世不會得到解決，然後咱們寫個 SwiftUI 選字窗將 IMKInputController 設為 ObservableObject。
知會 Apple 只是一個必須的步驟，剩下的都是他們自己的內務。

**Comment by ShikiSuen** [comment]
該故障被我找到解決方法了。我稍後推 commit 修正。

cc @xhacker 這個 API 運行前必須得給當前的 IMKCandidates instance 運行 `setSelectionKeysKeylayout()`。Xcode 的說明手冊得將這個要求寫在上面。

**Comment by y1lichen** [comment]
已修正！選字選可正常顯示0-8
