### ISSUE TITLE
輸入時只顯示完全匹配字碼的字元

### ISSUE THREAD

**Issue by y1lichen** [y1lichen/ilimi-inputmethod#16]

**Comment by ShikiSuen** [comment]
這個功能不妨做成 optional 吧，允許使用者手動啟用或停用。

**Comment by y1lichen** [comment]
> 這個功能不妨做成 optional 吧，允許使用者手動啟用或停用。

原廠蝦米只顯示完全匹配字碼的字元。考量讓使用者有更大的使用彈性，會將此做為optional項
