### ISSUE TITLE
英雄聯盟崩潰問題解決方法。

### ISSUE THREAD

**Issue by ShikiSuen** [y1lichen/ilimi-inputmethod#3]
我之前的 setWindowLevel 計算方法會導致英雄聯盟崩潰：
https://github.com/y1lichen/ilimi-inputmethod/blob/1e8817c8533729cb533acee4d3316f252c2b8261/ilimi/IlimiInputController.swift#L153-L157

請換成：
```swift
    func ensureWindowLevel(client sender: Any!) {
        candidates.setWindowLevel(UInt64(CGShieldingWindowLevel() + 2))
    }
```

**Comment by y1lichen** [comment]
已修正！感謝
https://github.com/y1lichen/ilimi-inputmethod/commit/213daf2a0460a802e654db391adeca172840de53
